CREATE TABLE "token_allocations" (
	"id" serial PRIMARY KEY NOT NULL,
	"token_id" integer,
	"description" text,
	"percentage" numeric(5, 2),
	"wallet_address" varchar(255) NOT NULL,
	"lockup_period" integer,
	"vesting_enabled" boolean,
	"vesting_description" text,
	"vesting_percentage" numeric(5, 2),
	"vesting_cliff" integer,
	"vesting_duration" integer,
	"vesting_interval" integer,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "tokens" (
	"id" serial PRIMARY KEY NOT NULL,
	"address" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"symbol" varchar(50) NOT NULL,
	"description" text,
	"supply" varchar(100) NOT NULL,
	"decimals" varchar(10) NOT NULL,
	"avatar_url" text,
	"banner_url" text,
	"selected_template" varchar(100) NOT NULL,
	"selected_pricing" varchar(100) NOT NULL,
	"selected_exchange" varchar(100) NOT NULL,
	"website" text,
	"twitter" text,
	"telegram" text,
	"discord" text,
	"farcaster" text,
	"initial_price" varchar(100),
	"final_price" varchar(100),
	"target_raise" varchar(100),
	"reserve_ratio" varchar(100),
	"curve_type" varchar(50),
	"launch_liquidity_on_name" varchar(100),
	"liquidity_source" varchar(50),
	"liquidity_data" jsonb,
	"liquidity_type" varchar(50),
	"liquidity_percentage" integer,
	"liquidity_lockup_period" integer,
	"is_auto_bot_protection_enabled" boolean,
	"is_auto_listing_enabled" boolean,
	"is_price_protection_enabled" boolean,
	"mint_fee" numeric(10, 2),
	"transfer_fee" numeric(10, 2),
	"burn_fee" numeric(10, 2),
	"fee_recipient_address" varchar(255),
	"admin_controls_enabled" boolean,
	"admin_controls_wallet_address" varchar(255),
	"soft_cap" varchar(100),
	"hard_cap" varchar(100),
	"schedule_launch_enabled" boolean,
	"launch_date" timestamp,
	"end_date" timestamp,
	"minimum_contribution" varchar(100),
	"maximum_contribution" varchar(100),
	"token_price" varchar(100),
	"max_token_per_wallet" varchar(100),
	"distribution_delay" integer,
	"revoke_mint_authority_enabled" boolean,
	"revoke_mint_authority_wallet_address" varchar(255),
	"revoke_freeze_authority_enabled" boolean,
	"revoke_freeze_authority_wallet_address" varchar(255),
	"admin_wallet_address" varchar(255),
	"admin_structure" varchar(50),
	"token_owner_wallet_address" varchar(255),
	"number_of_signatures" integer,
	"mint_authority_wallet_address" varchar(255),
	"freeze_authority_wallet_address" varchar(255),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "token_allocations" ADD CONSTRAINT "token_allocations_token_id_tokens_id_fk" FOREIGN KEY ("token_id") REFERENCES "public"."tokens"("id") ON DELETE cascade ON UPDATE no action;