const SOL_NETWORK = process.env.PUBLIC_SOL_NETWORK || 'testnet';
const HELIUS_API_KEY = process.env.PUBLIC_HELIUS_API_KEY;
const WALLET_CONNECT_PROJECT_ID = process.env.PUBLIC_WALLET_CONNECT_PROJECT_ID;
const ALCHEMY_API_KEY = process.env.PUBLIC_ALCHEMY_API_KEY;
const NEAR_NETWORK = process.env.PUBLIC_NEAR_NETWORK;
const NEAR_WALLET_CONNECT_PROJECT_ID = process.env.PUBLIC_WALLET_CONNECT_PROJECT_ID || "dba65fff73650d32ae5157f3492c379e";
const SOL_PRIVATE_KEY = process.env.PUBLIC_SOL_PRIVATE_KEY
const EVM_NETWORK = process.env.PUBLIC_EVM_NETWORK;

export { 
  SOL_NETWORK, 
  HELIUS_API_KEY, 
  WALLET_CONNECT_PROJECT_ID, 
  ALCHEMY_API_KEY,
  NEAR_NETWORK,
  NEAR_WALLET_CONNECT_PROJECT_ID,
  SOL_PRIVATE_KEY,
  EVM_NETWORK
};