const SOL_NETWORK = process.env.PUBLIC_SOL_NETWORK || 'devnet';
const HELIUS_API_KEY = process.env.PUBLIC_HELIUS_API_KEY;
const WALLET_CONNECT_PROJECT_ID = process.env.PUBLIC_WALLET_CONNECT_PROJECT_ID;
const ALCHEMY_API_KEY = process.env.PUBLIC_ALCHEMY_API_KEY;
const NEAR_NETWORK = process.env.PUBLIC_NEAR_NETWORK;
const NEAR_WALLET_CONNECT_PROJECT_ID = process.env.PUBLIC_WALLET_CONNECT_PROJECT_ID || "dba65fff73650d32ae5157f3492c379e";
const SOL_PRIVATE_KEY = process.env.PUBLIC_SOL_PRIVATE_KEY
const EVM_NETWORK = process.env.PUBLIC_EVM_NETWORK;
const NODE_ENV = process.env.PUBLIC_NODE_ENV
const TATUM_API_KEY = NEAR_NETWORK == "mainnet" ? process.env.PUBLIC_TATUM_API_KEY_MAINNET : process.env.PUBLIC_TATUM_API_KEY_TESTNET
const PINATA_API_KEY = process.env.PUBLIC_PINATA_API_KEY
const JWT_PINATA_SECRET = process.env.PUBLIC_JWT_PINATA_SECRET


export { 
  NODE_ENV,
  SOL_NETWORK, 
  HELIUS_API_KEY, 
  WALLET_CONNECT_PROJECT_ID, 
  ALCHEMY_API_KEY,
  NEAR_NETWORK,
  NEAR_WALLET_CONNECT_PROJECT_ID,
  SOL_PRIVATE_KEY,
  EVM_NETWORK,
  TATUM_API_KEY,
  PINATA_API_KEY,
  JWT_PINATA_SECRET
};